# Generated by Django 5.0.6 on 2025-08-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="loginpagesettings",
            options={
                "verbose_name": "Login Page Setting",
                "verbose_name_plural": "Login Page Settings",
            },
        ),
    ]
