[tool.black]
line-length = 88
target-version = ["py312"]
exclude = ["node_modules", "static"]

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = ["node_modules", "static"]

