# Generated by Django 5.0.6 on 2025-08-16 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_sitebranding"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContainerConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("icon", models.TextField(blank=True, null=True)),
                ("route", models.CharField(max_length=200)),
                ("allowed_roles", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
