# Generated by Django 5.0.6 on 2025-08-17 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_containerconfig"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="aiprovidersettings",
            options={
                "verbose_name": "AI Provider Setting",
                "verbose_name_plural": "AI Provider Settings",
            },
        ),
        migrations.AlterModelOptions(
            name="container",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Container",
                "verbose_name_plural": "Containers",
            },
        ),
        migrations.AlterModelOptions(
            name="containerconfig",
            options={
                "ordering": ["order"],
                "verbose_name": "Container Config",
                "verbose_name_plural": "Container Configs",
            },
        ),
        migrations.AlterModelOptions(
            name="sitebranding",
            options={
                "verbose_name": "Site Branding",
                "verbose_name_plural": "Site Branding",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={
                "verbose_name": "User Profile",
                "verbose_name_plural": "User Profiles",
            },
        ),
    ]
