# Generated by Django 5.0.6 on 2025-08-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_alter_aiprovidersettings_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="container",
            name="icon",
            field=models.TextField(default="icons/default.svg"),
        ),
    ]
